  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs: compile
    if: success()
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME,, }}:latest .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME,, }}:latest

